### ISSUE TITLE
配置完成，机器人不回复

### ISSUE THREAD

**Issue by SuperGGB0** [the-lazy-me/QChatGPT-Wiki#16]
在按照官方文档进行配置结束之后，运行main.py，结果如下：
![image](https://github.com/user-attachments/assets/6cf01435-04ea-465f-9748-ea27886de325)
但是当我用账号给机器人账号发消息，能接受到但是无法获得回复，并且cmd上也无报错？

**Comment by the-lazy-me** [comment]
这里不解答问题，加群619154800询问
