### ISSUE TITLE
使用第三方接口gpt的问题

### ISSUE THREAD

**Issue by Arturia169** [the-lazy-me/QChatGPT-Wiki#9]
按照教程打开了provider.json文件对API接口进行更改，并填写了第三方gpt给的api地址，但是在对话中一直连接失败，这个地址在使用其他gpt软件时是可以正常访问的，但是机器人不行
![QQ截图20240623103705](https://github.com/the-lazy-me/QChatGPT-Wiki/assets/69199123/40cb0faf-c863-4f0e-80e7-2f595812d596)
![QQ截图20240623103742](https://github.com/the-lazy-me/QChatGPT-Wiki/assets/69199123/b25fceda-a5d2-427f-8fab-31a5895fdf18)
。

**Comment by the-lazy-me** [comment]
到项目仓库提issue
